apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-path-pvc
  annotations:
    models/storage-path: "models"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 128Mi
